version: '3.8'

services:
  envoy:
    image: envoyproxy/envoy:v1.34-latest
    ports:
      - "8080:8080"
      - "9901:9901"  # Envoy admin interface
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    network_mode: "host"